name: Sync Space Secrets
run-name: ${{ github.actor }} syncing secrets
on:
  workflow_dispatch: {}
  push:
    branches:
    - "main"
    paths:
    - terraform/**
env:
  SPACE: warroyo-dev
jobs:
  sync-secrets:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
      - uses: hashicorp/setup-terraform@v3
      - name: Install Tanzu CLI
        run: |
          export TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER=no
          wget https://github.com/vmware-tanzu/tanzu-cli/releases/download/v1.5.1/tanzu-cli-linux-amd64.tar.gz -O /tmp/tanzu.tar.gz
          tar -xvf /tmp/tanzu.tar.gz -C /tmp
          install /tmp/v1.5.1/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
          tanzu config eula accept
          tanzu init
          tanzu version

      - name: Install tanzu plugins
        run: |
          tanzu plugin install --group vmware-tanzu/app-developer

            
      - name: set space context
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          TANZU_CLI_CLOUD_SERVICES_ORGANIZATION_ID: 77aee83b-308f-4c8e-b9c4-3f7a6f19ba75
        run: |
            tanzu login
            tanzu project use AMER-West
            tanzu space use $SPACE

      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init -backend-config="key=${{env.SPACE}}.terraform.tfstate"

      - name: Terraform Apply
        env:
          KUBECONFIG: ~/.config/tanzu/kube/config
          TF_VAR_key_vault_name: dev-space-secrets
          TF_VAR_key_vault_rg_name: tpk8s-secrets-example
          TF_VAR_az_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve -input=false